-- MySQL Script generated by MySQL Workbench
-- Tue Dec  6 12:52:15 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema portaldomalte
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema portaldomalte
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `portaldomalte` DEFAULT CHARACTER SET utf8 ;
USE `portaldomalte` ;

-- -----------------------------------------------------
-- Table `portaldomalte`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portaldomalte`.`user` (
  `id` VARCHAR(36) NOT NULL auto_increment,
  `first_name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(50) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `birthdate` DATE NOT NULL,
  `phone` VARCHAR(11) NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portaldomalte`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portaldomalte`.`address` (
  `id` VARCHAR(36) NOT NULL,
  `cep` VARCHAR(10) NULL,
  `number` VARCHAR(5) NULL,
  `street` VARCHAR(45) NULL,
  `district` VARCHAR(45) NULL,
  `city` VARCHAR(50) NULL,
  `state` VARCHAR(45) NULL,
  `user_id` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  INDEX `fk_address_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_address_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `portaldomalte`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portaldomalte`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portaldomalte`.`category` (
  `id` INT NOT NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portaldomalte`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portaldomalte`.`product` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `amount` VARCHAR(45) NULL,
  `image` VARCHAR(45) NULL,
  `value` DECIMAL(10) NULL,
  `user_id` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_product_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `portaldomalte`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portaldomalte`.`category_has_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portaldomalte`.`category_has_product` (
  `category_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`category_id`, `product_id`),
  INDEX `fk_category_has_product_product1_idx` (`product_id` ASC) VISIBLE,
  INDEX `fk_category_has_product_category1_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_category_has_product_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `portaldomalte`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_category_has_product_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `portaldomalte`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB; 


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
